language: node_js
node_js:
  - "6"

addons:
  code_climate:
    repo_token: 6311d1210370d1d6590fa1fc6688b5d146cb3f996c2213487a4b5cd42eea8e67

install:
    - npm i

script: 
    - npm test

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
